In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
filepath = r'C:\Users\parim\Downloads\Advertising (1).csv' 
df = pd.read_csv(filepath)

In [3]:
df = df.drop('ID',axis=1)

In [4]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X=df.drop('Sales',axis=1)

In [6]:
y=df['Sales']

In [7]:
from sklearn.preprocessing import PolynomialFeatures

In [8]:
polynomial_converter=PolynomialFeatures(degree=3,include_bias=False)

In [9]:
poly_features=polynomial_converter.fit_transform(X)

In [10]:
X.shape

(200, 3)

In [11]:
poly_features.shape

(200, 19)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [14]:
X_train.shape

(140, 19)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler =StandardScaler()

In [17]:
#we do not want information leaking from test state

scaler.fit(X_train)

StandardScaler()

In [18]:
X_train=scaler.transform(X_train)

In [19]:
X_test=scaler.transform(X_test)

In [20]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [21]:
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [22]:
from sklearn.linear_model import Ridge

In [23]:
# help(Ridge)

In [24]:
ridge_model=Ridge(alpha=10)

In [25]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [26]:
test_prediction=ridge_model.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [28]:
MAE=mean_absolute_error(y_test,test_prediction)

In [29]:
MAE

0.5774404204714166

In [30]:
RMSE=np.sqrt(mean_squared_error(y_test,test_prediction))

In [31]:
RMSE

0.8946386461319648

In [32]:
from sklearn.linear_model import RidgeCV#perform crossvalidations for alpha value ,best alpha value perfomance based of cross validation,cross validation - average error metric for all of these

In [47]:
ridge_cv_model=RidgeCV(alphas=(0.1,1.0,10.0),scoring='neg_mean_absolute_error')#how many folds we are going to do in cross validation

In [48]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [49]:
ridge_cv_model.alpha_

0.1

In [ ]:
#what was it using to measure the best performing alpha -we use scring metric

In [45]:
from sklearn.metrics._scorer import _SCORERS

In [46]:
_SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_root_mean_squared_log_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro',

In [50]:
test_prediction=ridge_cv_model.predict(X_test)

In [51]:
MAE=mean_absolute_error(y_test,test_prediction)

In [54]:
MAE

0.42737748843375084

In [55]:
RMSE=np.sqrt(mean_squared_error(y_test,test_prediction))

In [56]:
RMSE

0.6180719926926787

In [57]:
#we did tuning MAE=0.42 caomparing alpha value of 10 MAE was 0.57 on the test state we found better alphava value using ridge an 

In [58]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [59]:
# LASSO-least absolute shrinkage and selection operater

In [62]:
from sklearn.linear_model import LassoCV

In [ ]:
#alpha is basicaly lambda tuning hyper paramter

In [82]:
lasso_cv_model=LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=100000)#max_iter=1000000#epsilon default value taken eps smaller larger subset of possible values,5 fold cross validation

In [83]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=100000)

In [84]:
lasso_cv_model.alpha_

0.004943070909225831

In [85]:
test_predictions=lasso_cv_model.predict(X_test)

In [86]:
MAE=mean_absolute_error(y_test,test_predictions)

In [87]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))

In [88]:
MAE


0.4335034618590074

In [89]:
RMSE

0.6063140748984036

In [90]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [91]:
#elastic net

In [92]:
  #lasso is able to shrink coefficients to zero
  #elastic net allows us to combine l1 and l2

In [93]:
#elastic net

In [94]:
from sklearn.linear_model import ElasticNetCV

In [95]:
elastic_cv_model=ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps=0.001,n_alphas=100,max_iter=1000000)

In [96]:
elastic_cv_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [98]:
elastic_cv_model.l1_ratio_


1.0

In [99]:
elastic_cv_model.alpha_

0.004943070909225831

In [100]:
lasso_cv_model.alpha_

0.004943070909225831

In [102]:
test_predict=elastic_cv_model.predict(X_test)

In [104]:
MAE=mean_absolute_error(y_test,test_predict)

In [109]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predict))

In [107]:
MAE

0.4335034618590074

In [110]:
RMSE

0.6063140748984036